booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from userextend.forms import AuthenticationNewForm, PasswordChangeNewForm, PasswordResetNewForm, SetPasswordNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('userextend.urls')),
    path('', include('category.urls')),
    path('', include('product.urls')),
    path('', include('reservation.urls')),

    path('login/', views.LoginView.as_view(form_class=AuthenticationNewForm), name='login'),
    path('password_change/', views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm),
         name='password_change'),

    path('password_reset/', views.PasswordResetView.as_view(form_class=PasswordResetNewForm), name='password_reset'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(form_class=SetPasswordNewForm), name='password_reset_confirm'),

    path('', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home-page'),
]

reservation/urls.py
from django.urls import path

from reservation import views

urlpatterns = [
    path('create_reservation/', views.ReservationCreateView.as_view(), name='create_reservation'),
    path('list_of_reservations/', views.ReservationListView.as_view(), name='list-of-reservations'),
    path('update_reservation/<int:pk>/', views.ReservationUpdateView.as_view(), name='update-reservation'),
    path('delete_reservation/<int:pk>/', views.ReservationDeleteView.as_view(), name='delete-reservation'),
    path('detail_reservation/<int:pk>/', views.ReservationDetailView.as_view(), name='detail-reservation'),
]

reservation/models.py
from django.db import models

from product.models import Product


# Create your models here.

class Reservation(models.Model):
    date_in = models.DateField()
    date_out = models.DateField()

    def __str__(self):
        return f'{self.date_in}'

reservation/forms.py
from django import forms
from django.forms import Select, TextInput, DateInput

from reservation.models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

        widgets = {
            'date_in': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_out': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }


class ReservationUpdateForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

        widgets = {
            'reserved_by': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your name'}),
            'date_in': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_out': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

reservation/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from reservation.forms import ReservationForm, ReservationUpdateForm
from reservation.models import Reservation


# Create your views here.

class ReservationCreateView(PermissionRequiredMixin, CreateView, SuccessMessageMixin):
    template_name = 'reservation/create_reservation.html'
    model = Reservation
    form_class = ReservationForm
    success_url = reverse_lazy('list-of-reservations')
    success_message = 'Reservation was made successfully!'
    permission_required = 'reservation.add_reservation'

    def get_success_message(self, cleaned_data):
        return self.success_message.format(name=self.object.name)


class ReservationListView(PermissionRequiredMixin, ListView):
    template_name = 'reservation/list_of_reservations.html'
    model = Reservation
    context_object_name = 'all_reservations'
    permission_required = 'reservation.add_reservation'

    def get_queryset(self):
        return Reservation.objects.all()


class ReservationUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'reservation/update_reservation.html'
    model = Reservation
    form_class = ReservationUpdateForm
    success_url = reverse_lazy('list-of-reservations')
    permission_required = 'reservation.add_reservation'


class ReservationDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'reservation/delete_reservation.html'
    model = Reservation
    success_url = reverse_lazy('list-of-reservations')
    permission_required = 'reservation.add_reservation'


class ReservationDetailView(PermissionRequiredMixin, DetailView):
    template_name = 'reservation/detail_reservation.html'
    model = Reservation
    permission_required = 'reservation.add_reservation'

templates/reservation/create_reservation.html
{% extends 'base.html' %}
{% block title %} Create a new reservation {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new reservation</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reservation/delete_reservation.html
{% extends 'base.html' %}
{% block title %} Delete - {{ reservation }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Delete - {{ reservation }}</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <h4 class="text-center">Are you sure you want to delete {{ reservation }}?</h4>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-danger">Yes</button>
                            <a href="{% url 'list-of-reservations' %}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reservation/detail_reservation.html
{% extends 'base.html' %}
{% block title %} Details of {{ reservation }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card text-center">
                    <div class="card-header">
                        Details of reservation
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ reservation }}</h5>
                        <p class="card-text"><b>Reservation:</b>{{ reservation.product }}</p>
                    </div>
                    <div class="card-footer text-body-secondary">
                        <b>Reserved by:</b> {{ reservation.reserved_by }} <br>
                        <b>Date in:</b> {{ reservation.date_in }} <br>
                        <b>Date out:</b> {{ reservation.date_out }} <br>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'list-of-reservations' %}" class="btn btn-outline-dark">Return</a>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/reservation/list_of_reservations.html
{% extends 'base.html' %}
{% block title %} List of reservations {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% if all_reservations %}
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Product</th>
                            <th>Reserved by</th>
                            <th>Check in</th>
                            <th>Check out</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for reservation in all_reservations %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ reservation.product }}</td>
                                <td>{{ reservation.reserved_by }}</td>
                                <td>{{ reservation.date_in }}</td>
                                <td>{{ reservation.date_out }}</td>
                                <td>
                                    {% if perms.reservation.change_reservation or perms.reservations.delete_reservation or perms.reservation.view_reservation %}
                                        <div class="dropdown">
                                            <a class="btn btn-light dropdown-toggle" href="#" role="button"
                                               data-bs-toggle="dropdown" aria-expanded="false">More actions
                                            </a>
                                            <ul class="dropdown-menu">
                                                {% if perms.reservation.change_reservation %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'update-reservation' reservation.id %}">Update</a>
                                                    </li>
                                                {% endif %}
                                                {% if perms.reservation.delete_reservation %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'delete-reservation' reservation.id %}">Delete</a>
                                                    </li>
                                                {% endif %}
                                                {% if perms.reservation.view_reservation %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'detail-reservation' reservation.id %}">Details</a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    {% else %}
                                        No actions
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    There are no reservations available!
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/reservation/update_reservation.html
{% extends 'base.html' %}
{% block title %} Update - {{ reservation }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Update - {{ reservation }}</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn bnt-success">Save</button>
                            <a href="{% url 'list-of-reservations' %}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}